//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroastCastMessageProject.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BroastCastMessageDBEntities : DbContext
    {
        public BroastCastMessageDBEntities()
            : base("name=BroastCastMessageDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BCMMessage> BCMMessages { get; set; }
        public DbSet<BCMRegistration> BCMRegistrations { get; set; }
    }
}
